### ISSUE TITLE
Cannot change ObservableCollection during a CollectionChanged event.

### ISSUE THREAD

**Issue by DATA-GAP** [brianlagunas/PrismOutlook#2]
Brian, awesome series, thank you very much.  It has been very helpful getting up to speed on Prism.

However, ran into the above error message (Cannot change ObservableCollection during a CollectionChanged event) in my own project in DependentViewRegionBehavior.cs at this line:

dependentViews.ForEach(item => Region.RegionManager.Regions[item.Region].Add(item.View));

I've tried troubleshooting the issue, but I'm coming up short so far.  Any insights as to why this might be happening?

**Comment by brianlagunas** [comment]
Sorry, I have never seen that issue before, and I am using this adapter in many production applications. I hope you figure out soon. Good luck.
